version: '3.7'

services:

   postgres:
     image: ghandalf/postgres
     container_name: postgres
     hostname: postgres.ghandalf.ca
     ports: ['5432:5432']
     #restart: always
     environment:
        POSTGRES_PASSWORD: gh@nd@lf!
     volumes:
      - postgres-data:/var/lib/postgresql/data:rw
     networks: ['ghandalf.ca']

  #  adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

networks: { ghandalf.ca:{} }

volumes:
  postgres-data:
    driver: local