version: '3.7'

services:
   
   elasticsearch:
      container_name: elasticsearch
      deploy:
         replicas: 2
         update_config:
            parallelism: 2
            delay: 10s
         restart_policy:
            condition: on_failure
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
      labels:
        ca.ghandalf.service: "elasticsearch"
        ca.ghandalf.description: "For searching and indexing data"
      networks:
         - analytic_net
      ports:
         - "9200:9200"
         - "9300:9300"
      restart: always
      volumes: 
        - type: volume
          source: elastic-data
          target: /data/server/analytic/elasticsearch
          
   kibana:
      container_name: kibana
      depends_on:
         - elasticsearch
      deploy:
         replicas: 2
         update_config:
            parallelism: 2
            delay: 10s
         restart_policy:
            condition: on_failure
      environment: 
        - ELASTICSEARCH_URL=http://localhost:9200
      image: docker.elastic.co/kibana/kibana:6.4.3
      labels:
        ca.ghandalf.service: "kibana"
        ca.ghandalf.description: "Data presentation and logs aggregation"
      networks:
         - analytic_net
      ports:
         - "5601:5601"
      restart: always

networks:
   analytic_net: 

volumes:
  elastic-data:
    driver: local