version: '3.7'

services:
   
   elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
      labels:
        ca.ghandalf.service: "elasticsearch"
        ca.ghandalf.description: "For searching and indexing data"
      networks:
         - analytic_net
      ports:
         - "9200:9200"
      volumes: 
        - type: volume
          source: elastic-data
          target: /data/server/analytic/elasticsearch
      restart: always

   kibana:
      container_name: kibana
      depends_on:
        - elasticsearch
      environment: 
        - ELASTICSEARCH_URL=http://es:9200
      image: docker.elastic.co/kibana/kibana:6.4.3
      labels:
        ca.ghandalf.service: "kibana"
        ca.ghandalf.description: "Data presentation and logs aggregation"
      networks:
         - analytic_net
      ports:
         - "5601:5601"
      restart: always

networks:
   analytic_net:

volumes:
  elastic-data:
    driver: local